### ISSUE TITLE
Feature: Start tail on connection and stop when no connections

### ISSUE THREAD

**Issue by duzun** [apocas/dashode#2]
It would be nice if tail starts only on connection and stops when no connections.

I would like to be able to run multiple instances of dashode for different websites on the same server all the time, so that I don't have to connect over ssh to start a dashode instance for a speciffic website.
But this would add some extra load to the server (constant IO).

Nice tool ! :-)

**Comment by apocas** [comment]
I already decoupled log collection from the dashboard :)
Allowing to have multiple collectors (remote or local) for 1 or multiple dashboards.

I will push it today or tomorrow.

**Comment by duzun** [comment]
Sounds great!

**Comment by duzun** [comment]
#4 should close this issue
